export const GET_START = 'GET_START';
export const GET_CASE_STUDIES = 'GET_CASE_STUDIES';
export const GET_CASE_STUDIES_SUCCESS = 'GET_CASE_STUDIES_SUCCESS';
export const GET_CASE_STUDIES_FAIL = 'GET_CASE_STUDIES_FAIL';
export const GET_CASE_STUDY = 'GET_CASE_STUDY';
